name: CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure
        run: cmake -S. -Bbuild -DCMAKE_INSTALL_PREFIX=install

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

  windows-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build
